version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-2"
    ECS_CLUSTER: "diagram-cluster"
    S3_BUCKET: "diagram-output-407668821695-1"
    LAMBDA_RESPONDER: "slack-diagram-responder"

phases:
  pre_build:
    commands:
      - echo "=============================="
      - echo "RECEIVED ENV VARIABLES"
      - echo "=============================="
      - env | sort
      - echo "=============================="
      - echo "Checking required variables..."
      - |
        REQUIRED_VARS=("JOB_ID" "PROMPT" "CHANNEL_ID" "USER_ID")
        ALL_PRESENT=true
        for VAR in "${REQUIRED_VARS[@]}"; do
          if [ -z "${!VAR}" ]; then
            echo "ERROR Missing env var $VAR"
            ALL_PRESENT=false
          else
            echo "OK $VAR is ${!VAR}"
          fi
        done
        if [ "$ALL_PRESENT" = false ]; then
          exit 1
        fi
        echo "All required variables are present"
      - echo "=============================="
      
  build:
    commands:
      - echo "Build phase starting"
      - echo "JOB_ID is $JOB_ID"
      - echo "PROMPT is $PROMPT"
      - echo "CHANNEL_ID is $CHANNEL_ID"
      - echo "USER_ID is $USER_ID"
      - echo "Build phase complete"
      
  post_build:
    commands:
      - echo "Post-build complete"
