version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-2"
    ECS_CLUSTER: "diagram-cluster"
    S3_BUCKET: "diagram-output-407668821695-1"
    LAMBDA_RESPONDER: "slack-diagram-responder"

phases:
  pre_build:
    commands:
      - echo "=============================="
      - echo "RECEIVED ENV VARIABLES"
      - echo "=============================="
      - env | sort
      - echo "=============================="
      - echo "Checking required variables..."
      - test -n "$JOB_ID" || (echo "ERROR Missing JOB_ID" && exit 1)
      - echo "OK JOB_ID is $JOB_ID"
      - test -n "$PROMPT" || (echo "ERROR Missing PROMPT" && exit 1)
      - echo "OK PROMPT is $PROMPT"
      - test -n "$CHANNEL_ID" || (echo "ERROR Missing CHANNEL_ID" && exit 1)
      - echo "OK CHANNEL_ID is $CHANNEL_ID"
      - test -n "$USER_ID" || (echo "ERROR Missing USER_ID" && exit 1)
      - echo "OK USER_ID is $USER_ID"
      - echo "All required variables are present"
      - echo "=============================="
      
  build:
    commands:
      - echo "Build phase starting"
      - echo "JOB_ID is $JOB_ID"
      - echo "PROMPT is $PROMPT"
      - echo "CHANNEL_ID is $CHANNEL_ID"
      - echo "USER_ID is $USER_ID"
      - echo "Build phase complete"
      
  post_build:
    commands:
      - echo "Post-build complete"
