version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-2"
    ECS_CLUSTER: "diagram-cluster"
    S3_BUCKET: "diagram-output-407668821695-1"
    LAMBDA_RESPONDER: "slack-diagram-responder"

phases:
  pre_build:
    commands:
      - echo "=============================="
      - echo "   RECEIVED ENV VARIABLES"
      - echo "=============================="
      - env | sort
      - echo "=============================="
      - echo "Checking required variables..."
      # Use multi-line string block with pipe | to avoid YAML parsing issues
      - |
        REQUIRED_VARS=("JOB_ID" "PROMPT" "CHANNEL_ID" "USER_ID")
        for VAR in "${REQUIRED_VARS[@]}"; do
          if [ -z "${!VAR}" ]; then
            echo "❌ ERROR: Missing env var: $VAR"
            exit 1
          else
            echo "✔ $VAR = ${!VAR}"
          fi
        done
      - echo "All required variables are present."
      - echo "=============================="
      
  build:
    commands:
      - echo "Build phase starting..."
      - echo "JOB_ID     : $JOB_ID"
      - echo "PROMPT     : $PROMPT"
      - echo "CHANNEL_ID : $CHANNEL_ID"
      - echo "USER_ID    : $USER_ID"
      - echo "Starting your actual logic here..."
      # Your real logic here
      
  post_build:
    commands:
      - echo "Post-build complete"
