version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-2"
    ECS_CLUSTER: "diagram-cluster"
    S3_BUCKET: "diagram-output-407668821695-1"
    LAMBDA_RESPONDER: "slack-diagram-responder"

phases:
  pre_build:
    commands:
      - echo "Starting diagram generation for job $JOB_ID"
      - echo "Prompt: $PROMPT"
      - echo "Channel: $CHANNEL_ID"

  build:
    commands:
      - |
        # Validate input
        if [ -z "$JOB_ID" ] || [ -z "$PROMPT" ]; then
          echo "ERROR: JOB_ID or PROMPT is empty!"
          exit 1
        fi

      - |
        # Update DynamoDB status
        aws dynamodb update-item \
          --table-name diagram-jobs \
          --key "{\"job_id\": {\"S\": \"$JOB_ID\"}}" \
          --update-expression "SET #status = :status, updated_at = :updated" \
          --expression-attribute-names "{\"#status\": \"status\"}" \
          --expression-attribute-values "{\":status\": {\"S\": \"processing\"}, \":updated\": {\"N\": \"$(date +%s)\"}}"

      - echo "Starting MCP Server..."

      - |
        # Run MCP Server task
        MCP_TASK_ARN=$(aws ecs run-task \
          --cluster $ECS_CLUSTER \
          --launch-type FARGATE \
          --task-definition mcp-server-task \
          --network-configuration "awsvpcConfiguration={subnets=[subnet-0ccc4118f84577e26,subnet-0355b42dde3f68310],securityGroups=[sg-0cf06069862b4eb35],assignPublicIp=DISABLED}" \
          --query 'tasks[0].taskArn' \
          --output text)

      - echo "MCP Task ARN: $MCP_TASK_ARN"
      - sleep 30

      - |
        # Get MCP IP
        MCP_IP=$(aws ecs describe-tasks \
          --cluster $ECS_CLUSTER \
          --tasks $MCP_TASK_ARN \
          --query 'tasks[0].attachments[0].details[?name==`privateIPv4Address`].value' \
          --output text)

      - echo "MCP Server IP: $MCP_IP"

      - |
        if [ -z "$MCP_IP" ]; then
          echo "ERROR: Failed to get MCP server IP"
          exit 1
        fi

      - echo "Starting Worker..."

      - |
        # Run worker task
        WORKER_TASK_ARN=$(aws ecs run-task \
          --cluster $ECS_CLUSTER \
          --launch-type FARGATE \
          --task-definition worker-task \
          --network-configuration "awsvpcConfiguration={subnets=[subnet-0ccc4118f84577e26,subnet-0355b42dde3f68310],securityGroups=[sg-0cf06069862b4eb35],assignPublicIp=DISABLED}" \
          --overrides "{
            \"containerOverrides\": [{
              \"name\": \"worker\",
              \"environment\": [
                {\"name\": \"JOB_ID\", \"value\": \"$JOB_ID\"},
                {\"name\": \"PROMPT\", \"value\": \"$PROMPT\"},
                {\"name\": \"OUTPUT_BUCKET\", \"value\": \"$S3_BUCKET\"},
                {\"name\": \"OUTPUT_KEY_PREFIX\", \"value\": \"diagrams/\"},
                {\"name\": \"MCP_SERVICE_URL\", \"value\": \"http://$MCP_IP:5000/render\"},
                {\"name\": \"AWS_REGION\", \"value\": \"$AWS_DEFAULT_REGION\"},
                {\"name\": \"MODE\", \"value\": \"single\"}
              ]
            }]
          }" \
          --query 'tasks[0].taskArn' \
          --output text)

      - echo "Worker Task ARN: $WORKER_TASK_ARN"
      - sleep 60

      - |
        # Poll worker task
        for i in {1..10}; do
          STATUS=$(aws ecs describe-tasks \
            --cluster $ECS_CLUSTER \
            --tasks $WORKER_TASK_ARN \
            --query 'tasks[0].lastStatus' \
            --output text)
          echo "Worker status: $STATUS ($i/10)"
          if [ "$STATUS" = "STOPPED" ]; then
            break
          fi
          sleep 30
        done

  post_build:
    commands:
      - |
        # Verify S3 output
        if aws s3 ls s3://$S3_BUCKET/diagrams/$JOB_ID.png; then
          echo "Diagram OK"
        else
          echo "Diagram missing"
        fi
